version: "3.8"
services:
  proxy:
    image: jwilder/nginx-proxy:alpine
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "${NGINX_PORT}:80"

  frontend:
    container_name: sergeym-frontend-react
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/docker-react-sample
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    environment:
      CHOKIDAR_USEPOLLING: "true"

  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql

  myapp:
    container_name: sergeym-backend-laravel
    image: docker.io/bitnami/laravel:9
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=mysql
      - DB_PORT=${MYSQL_PORT}
      - DB_USERNAME=${MYSQL_USER}
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - './backend:/app:consistent'
    depends_on:
      - mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"
    environment:
      VIRTUAL_HOST: ${ADMINER_VIRTUAL_HOST}
    depends_on:
      - proxy
